# Generated by Django 4.1.7 on 2023-03-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date_pupl',
            field=models.DateTimeField(verbose_name='Дата выхода:'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='directions',
            field=models.ManyToManyField(to='anime.direction', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='gener',
            field=models.ManyToManyField(to='anime.gener', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titel',
            field=models.CharField(max_length=100, verbose_name='Название аниме:'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Биография:'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Фамилия и Имя:'),
        ),
        migrations.AlterField(
            model_name='gener',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='gener',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название жанра:'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emeil', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text_reviews', models.TextField(max_length=500, verbose_name='Текст озыва')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
